### PR TITLE
27 organizar o repositório

### PR DESCRIPTION
**Pull request by giovanni1106**
- [ ] Histórico de versão padronizado
- [ ] Bibliografia atualizada
- [ ] Fontes ABNT aplicadas
- [ ] Link de imagens corrigidos

### CODE REVIEW

**Review by giovanni1106 — COMMENTED** [review]
Alterações revisadas

**Comment by LucasBergholz** [comment]
We have some major problems regarding the way html and markdown are dealing with links. For now, i will not accept the PR and wait for our sprint review meeting to fix these problems.

**Review by LucasBergholz — APPROVED** [review]
Well done Gigi! Excelent work, as always <3

**Review by igorpenhaa — APPROVED** [review]
excellent Work, Giovanni

**Pull request merged**
